version: '3.3'
services:
    mongo:
        ports:
            - '27017:27017'
        container_name: mongoDB
        restart: always
        logging:
            options:
                max-size: 1g
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongoadmin
            - MONGO_INITDB_ROOT_PASSWORD=bdung
        image: mongo
        #privileged: true
        #syslog-ng:
        #ports:
        #    - '514:514/udp'
        #    - '601:601/tcp'
        #network_mode: host
        #container_name: syslog-ng
        #restart: always
        #logging:
        #    options:
        #        max-size: 1g
        #image: my-syslog-ng:updated
        #image: muruganpalc/my-syslog-ng:syslog-ng
        #entrypoint: "sleep 100000"
        #entrypoint: ["syslog-ng", "-F", "-f", "/etc/syslog-ng/syslog-ng.conf"]
        #entrypoint: ["/entrypoint.sh"]
        #volumes:
        #    # "$PWD/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf"
        # - "$PWD/mongo_change_stream.py:/mongo_change_stream.py"
              #cap_add:
              #   - NET_BIND_SERVICE
              # - NET_BROADCAST
              # - NET_RAW
              #- DAC_READ_SEARCH
              #- DAC_OVERRIDE
              #- CHOWN
              #- SYSLOG
        #privileged: true
        #depends_on:
        #    - mongo

